### PR TITLE
Recommend friend bugfix

### LINKED ISSUE #151: Recommended Friends Staying Upon Friend Request Sending
From Slack:

Hey guys, you’ll notice on the mobile app that if you send a friend request to someone in your Friends -> “recommended friends” section, you’ll still get them as recommended friends. I tried to fix this logic today with a few PRs but guess it’s still an issue.
Could anyone take a second look at what I might be doing wrong inside of FriendRequestService::getRecommendedFriendsForUserId(), on the main branch?

### PR DESCRIPTION
**Pull request by evannawfal**
Adjusted getRecommendedFriendsForUserId in UserService to now:

- Only recommend friends that you have not already sent a request to
- Only recommend friends that you do not have a request from
- Exclude the current user from the list of recommendations

Resolves #151

### CODE REVIEW

**Review by ShaneMander — APPROVED** [review]
Looks like it should work

File: src/main/java/com/danielagapov/spawn/Services/User/UserService.java [hunk 1]
```diff
@@ -396,24 +396,38 @@ public List<RecommendedFriendUserDTO> getRecommendedFriendsForUserId(UUID userId
             // Fetch the requesting user's friends
             List<UUID> requestingUserFriendIds = getFriendUserIdsByUserId(userId);
 
-            // Create a set of the requesting user's friends for quick lookup
-            Set<UUID> requestingUserFriendSet = new HashSet<>(requestingUserFriendIds);
+            // Fetch users who have already received a friend request from the user
+            List<UUID> sentFriendRequestIds = friendRequestService.getSentFriendRequestsByUserId(userId)
```
Comment (Daggerpov) [inline src/main/java/com/danielagapov/spawn/Services/User/UserService.java:400]:
```suggestion
            List<UUID> sentFriendRequestReceiverUserIds = friendRequestService.getSentFriendRequestsByUserId(userId)
```
Old name was misleading someone to read it as the friend request ids, not the receiver user ids of those friend requests

File: src/main/java/com/danielagapov/spawn/Services/User/UserService.java [hunk 2]
```diff
@@ -396,24 +396,38 @@ public List<RecommendedFriendUserDTO> getRecommendedFriendsForUserId(UUID userId
...
+                    .stream()
+                    .map(FriendRequestDTO::receiverUserId)
+                    .collect(Collectors.toList());
+
+            // Fetch users who have sent a friend request to the user (pending requests)
+            List<UUID> receivedFriendRequestIds = friendRequestService.getIncomingFriendRequestsByUserId(userId)
```
Comment (Daggerpov) [inline src/main/java/com/danielagapov/spawn/Services/User/UserService.java:406]:
```suggestion
            List<UUID> receivedFriendRequestSenderUserIds = friendRequestService.getIncomingFriendRequestsByUserId(userId)
```
Same as above, for clarity

File: src/main/java/com/danielagapov/spawn/Services/User/UserService.java [hunk 3]
```diff
@@ -396,24 +396,38 @@ public List<RecommendedFriendUserDTO> getRecommendedFriendsForUserId(UUID userId
...
+                    .stream()
+                    .map(request -> request.getSenderUser().id())
+                    .collect(Collectors.toList());
 
-            // Collect friends of friends (excluding already existing friends and the user itself)
+            // Create a set of the requesting user's friends, sent requests, received requests, and self for quick lookup
```
Comment (Daggerpov) [inline src/main/java/com/danielagapov/spawn/Services/User/UserService.java:411]:
```suggestion
            // Create a set of the requesting user's friends, users they've sent requests to, users they've received requests from, and self for quick lookup
```

**Review by Daggerpov — CHANGES_REQUESTED** [review]
Really nice simplification of my logic, and fixing it by considering both directions of friend requests, which I missed. Great work! Just suggested a couple of readability changes to var names & comments

Plus, a little merge conflict from my PR, sorry about that. #155

**Review by Daggerpov — APPROVED** [review]
